# Generated by Django 5.1.6 on 2025-02-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_pdf', models.FileField(upload_to='questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
