# Generated by Django 5.1.6 on 2025-02-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathquestion',
            name='drawing',
            field=models.ImageField(blank=True, null=True, upload_to='drawings/'),
        ),
    ]
