# Generated by Django 5.1.6 on 2025-02-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_mathquestion_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mathquestion',
            name='drawing',
        ),
    ]
