# Generated by Django 5.1.6 on 2025-02-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_mathquestion_drawing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquestion',
            name='question_pdf',
            field=models.FileField(upload_to='media/questions/'),
        ),
    ]
